---
- name: check zinit install
  stat: path=/home/vagrant/.zinit/bin/zinit
  ignore_errors: True
  register: result

- name: install packages zinit
  become: vagrant
  ignore_errors: True
  shell: >
    touch /home/vagrant/.zshrc;
    yes | sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh)";
    source /home/vagrant/.zshrc;
    zinit self-update;
  when: not result.stat.exists
